name: jaystore
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1
#-----------PACKAGES---------------#
dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  intl: ^0.20.2
  url_launcher: ^6.3.2

#------Utility packages--------------#
http: ^1.5.0
intl: ^0.20.2
logger: ^2.6.1
url_launcher: ^6.3.2

# Icons
iconsax: ^0.0.8
iconsax_flutter: ^1.0.1
cupertino_icons: ^1.0.8
icon_to_text_extension_codespark: ^0.0.3
#State Management
get: ^4.7.2
get_storage: ^2.1.1

#product specific



#----------./PACKAGES END ------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  #--------LOCAL ASSETS -------------#
assets:
  - assets/logos/
  - assets/icons/
  - assets/images/

  #--------------LOCAL FONTS------------#
fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins-light.ttf
        we-ight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-RegularItalic.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-lightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalc.ttf
        weight: 500
        style: italic